name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master] 
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install && npm install --save-dev cross-env jest supertest cypress @testing-library/jest-dom @testing-library/react eslint eslint-plugin-cypress eslint-plugin-jest
      - name: Build
        run: npm run build:ui
      - name: Check style
        run: npm run lint
      - name: Run Backend tests
        run: npm run test:api
        shell: bash
        env:
          NODE_ENV: test
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      - name: E2E tests
        id: cypress
        uses: cypress-io/github-action@v5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: 3002
        with:
          command: npm run test:e2e
          start: npm run start:prod
          wait-on: http://localhost:5000
        
